[variables]
    NIXPACKS_PHP_VERSION = '8.3'

[phases.setup]
    nixPkgs = ['php83', 'php83Packages.composer', 'nodejs']

[phases.build]
    cmds = ['composer install --optimize-autoloader --no-dev', 'npm install && npm run build']

[start]
    cmd = 'php artisan serve --host 0.0.0.0 --port $PORT'
    